// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Q_lKLlPLEC9B2VkFFPJlH-tBpV-bZHk',
    appId: '1:885977086701:web:565b5e4bc5ca97136feae4',
    messagingSenderId: '885977086701',
    projectId: 'testcli-89d83',
    authDomain: 'testcli-89d83.firebaseapp.com',
    storageBucket: 'testcli-89d83.firebasestorage.app',
    measurementId: 'G-6S48ZPVZ9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLy_ZNcWrf4fXH2xz4SfjE8Sp75D_lKs',
    appId: '1:885977086701:android:3818e4a6b676c5bf6feae4',
    messagingSenderId: '885977086701',
    projectId: 'testcli-89d83',
    storageBucket: 'testcli-89d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUUgAYpYFa0gKuZwNpW7iXSGR9zxekp8',
    appId: '1:885977086701:ios:b26ca7b517193de76feae4',
    messagingSenderId: '885977086701',
    projectId: 'testcli-89d83',
    storageBucket: 'testcli-89d83.firebasestorage.app',
    iosBundleId: 'com.rasel.testCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaUUgAYpYFa0gKuZwNpW7iXSGR9zxekp8',
    appId: '1:885977086701:ios:b26ca7b517193de76feae4',
    messagingSenderId: '885977086701',
    projectId: 'testcli-89d83',
    storageBucket: 'testcli-89d83.firebasestorage.app',
    iosBundleId: 'com.rasel.testCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Q_lKLlPLEC9B2VkFFPJlH-tBpV-bZHk',
    appId: '1:885977086701:web:00cc3d6999f64a5a6feae4',
    messagingSenderId: '885977086701',
    projectId: 'testcli-89d83',
    authDomain: 'testcli-89d83.firebaseapp.com',
    storageBucket: 'testcli-89d83.firebasestorage.app',
    measurementId: 'G-HR0WV1G1Z1',
  );
}
